remote_theme: daviddarnes/alembic@main
plugins:
  - jekyll-remote-theme

title: Leep Dearning \| Codexistent
description: A collection of deep learning projects/mini projects.

author:
  name: Codexistent
